# Generated by Django 6.0.3 on 2026-04-03 13:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900, message='El año no puede ser anterior a 1900'), django.core.validators.MaxValueValidator(2031, message='El año no puede ser tan futuro')])),
                ('genre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('background_image', models.URLField(blank=True, max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0, message='La calificación no puede ser negativa'), django.core.validators.MaxValueValidator(10.0, message='La calificación no puede ser mayor a 10.0')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El número de episodio debe ser mayor a 0')])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(help_text='Duración en minutos', validators=[django.core.validators.MinValueValidator(1, message='La duración debe ser al menos 1 minuto'), django.core.validators.MaxValueValidator(300, message='La duración no puede exceder 300 minutos')])),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='backoffice.anime')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('anime', 'episode_number')},
            },
        ),
    ]
