# Generated by Django 6.0.3 on 2026-04-12 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(choices=[('TV-Y', 'TV-Y'), ('TV-PG', 'TV-PG'), ('TV-14', 'TV-14'), ('TV-MA', 'TV-MA'), ('R', 'R')], default='TV-14', max_length=10),
        ),
        migrations.AddField(
            model_name='anime',
            name='audio_type',
            field=models.CharField(choices=[('SUB', 'Subtitulado'), ('DUB', 'Doblado'), ('BOTH', 'Sub y Dub')], default='SUB', max_length=10),
        ),
        migrations.AddField(
            model_name='anime',
            name='episode_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_simulcast',
            field=models.BooleanField(default=False),
        ),
    ]
