# Generated by Django 6.0.3 on 2026-04-12 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_anime_age_rating_anime_audio_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_episode', models.IntegerField(default=0, help_text='Último episodio visto completamente', validators=[django.core.validators.MinValueValidator(0)])),
                ('watched', models.BooleanField(default=False, help_text='True si el usuario completó toda la serie')),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='backoffice.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch Progress',
                'verbose_name_plural': 'Watch Progress',
                'ordering': ['-last_watched'],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
