# Generated by Django 6.0.3 on 2026-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_watchprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_slug',
            field=models.CharField(blank=True, help_text='Slug para búsqueda en GogoAnime (ej: one-piece, naruto-shippuden)', max_length=255),
        ),
    ]
