# Generated by Django 6.0.4 on 2026-05-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_anime_anime_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='content_type',
            field=models.CharField(choices=[('SERIE', 'Serie'), ('PELÍCULA', 'Película'), ('OVA', 'OVA'), ('ESPECIAL', 'Especial')], default='SERIE', max_length=10),
        ),
    ]
