# Generated by Django 6.0.5 on 2026-05-05 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_anime_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
