# Generated by Django 6.0.3 on 2026-05-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_watchprogress_to_profile'),
        ('backoffice', '0005_anime_content_type'),
    ]

    operations = [
    ]
