# Generated by Django 6.0.5 on 2026-05-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_merge_20260506_1056'),
        ('backoffice', '0007_anime_dislikes'),
    ]

    operations = [
    ]
